import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState, useRef} from 'react'


export default function Home() {
  const inputRef = useRef();
  const [shortURL, setShortURL] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    const url = inputRef.current.value;
    
    const res = await fetch('/api/shortUrl', {
      body: JSON.stringify({
        url
      }),
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST'
    });
    const { shortUrl } = await res.json();
    setShortURL(shortUrl);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>URL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
           URL Shortener
        </h1>

        <p className={styles.description}>
          Acorta tus URL
        </p>

       <div>
            <form className={styles.card} onSubmit={handleSubmit}>
                <input type="text" className='styles.input'
                placeholder='Ingresa tu URL'  ref={inputRef} />
                         
                <button className={styles.button}>Acortar</button>
                <br/>
                <span className={styles.input}>
                  {shortURL}
                </span>
            </form>
        </div>  

      </main>
    </div>
  )
}
